### ISSUE TITLE
Queries not working anymore.

### ISSUE THREAD

**Issue by AlexanderProd** [fedehub93/gatsby-source-shopify-translations#11]
I've suddenly getting this errors when building my gatsby site using this plugin.

```
 ERROR #11321  PLUGIN

"gatsby-source-shopify-translations" threw an error while running the sourceNodes lifecycle:

Field 'metafields' is missing required arguments: identifiers
Field 'metafields' doesn't accept argument 'first'
Field 'edges' doesn't exist on type 'Metafield'
```

It is completely hindering me from doing anything. 

I've tried not querying any metafields but that didn't fix it. 

Do you have an idea why this could be the case. 

I suspect shopify made changes to the storefront API endpoint but `gatsby-source-shopify-translations` is still using an old version. I'm wondering if they just don't serve the old version of the API anymore. Which would be extremely annoying.

EDIT: 
I had to remove all translations in order to get gatsby to build. :/

**Comment by KevinBritten** [comment]
Hi Alexander, I ran into the same problem. It seems you're right that the API version that this package uses isn't served anymore. I'll submit a PR with my solution, you'll have to update any queries using metafields as the graphql schema has changed.

**Comment by AlexanderProd** [comment]
@KevinBritten Thanks for the PR, I've just tested your changes and It looks like it fixed everything. 👍🏻 
As you said my own grapql queries need to be updated, do you maybe have a documentation on how I should migrate those?

**Comment by KevinBritten** [comment]
No problem, glad to hear it!

metafields is now an array of objects, edges and nodes have been removed. So

```
            metafields {
              edges {
                node {
                  key
                  value
                }
              }
            }
```
            
becomes
            
```
            metafields {
                key
                value
            }
```
