### ISSUE TITLE
[ISSUE] Missing configurations - yotpoAppKey required

### ISSUE THREAD

**Issue by AlexanderProd** [fedehub93/gatsby-source-shopify-translations#4]
Hi,

during the gatsby develop process I always get the following error: 

```
Missing configurations - shopName, shopifyAccessToken and yotpoAppKey are required
```

I'm wondering what this yotpoAppKey is. 

On Shopify I'm using the `Etranslate` app but I've also tried it with `LangShop` and encountered the same problem. 

my `gatsby-config.js` file looks like this: 

```
{
   resolve: "gatsby-source-shopify",
   options: {
      password: process.env.SHOPIFY_SHOP_PASSWORD,
      storeUrl: process.env.GATSBY_SHOPIFY_STORE_URL,
      shopifyConnections: ["collections"],
   },
   {
      resolve: `gatsby-source-shopify-translations`,
      options: {
         shopName: process.env.GATSBY_SHOPIFY_STORE_URL,
         shopifyPassword: process.env.SHOPIFY_SHOP_PASSWORD,
         accessToken: process.env.GATSBY_SHOPIFY_ACCESS_TOKEN,
         defaultLang: "de",
         prefixDefault: true,
         //configPath: require.resolve("./locales/config.json"),
         locales: ["de", "en"],
         waitingGatsbySourceShopify: 5000,
   },
},
```

I'm trying this plugin with the official `gatsby-starter-shopify`. 
When I use only the `gatsby-source-shopify` without `gatsby-source-shopify-translations` then everything works fine.

**Comment by DennisKraaijeveld** [comment]
Are you sure there is no other plugin inside your project? I am using this plugin and it is working and looking at the src of this plugin, there is no yotpo to be found

Actually, there is. But only as console.log message, I guess thats a typo. 

```
exports.sourceNodes = async (gatsbyApi, pluginOptions) => {
  if (
    !pluginOptions.shopName ||
    !pluginOptions.shopifyPassword ||
    !pluginOptions.accessToken
  ) {
    console.log(
      "\nMissing configurations - shopName, shopifyAccessToken and yotpoAppKey are required"
    )
    process.exit(1)
  }

  await sourceAllNodes(gatsbyApi, pluginOptions)

  return
}
```

**Comment by fedehub93** [comment]
Hi,
yotpoAppKey was only a typo error on Missing configurations message that I fix right now. Thank you so much for that.

Regarding the mistake that happened to you, maybe the problem was in your .env file?

**Comment by AlexanderProd** [comment]
> Hi, yotpoAppKey was only a typo error on Missing configurations message that I fix right now. Thank you so much for that.
> 
> Regarding the mistake that happened to you, maybe the problem was in your .env file?

Oh I see. 
I don't think theres a problem in my .env file since the credentials work fine when I disable `gatsby-source-shopify-translations`. 

Or does `gatsby-source-shopify-translations` need them in a different format than `gatsby-source-shopify`

My .env looks like this:
```
GATSBY_STOREFRONT_ACCESS_TOKEN=6bxxxxxxxxxx
GATSBY_SHOPIFY_STORE_URL=xxxx.myshopify.com
SHOPIFY_SHOP_PASSWORD=shpat_xxxxxx
#GOOGLE_ANALYTICS_ID=XXX
```

**Comment by fedehub93** [comment]
Oh maybe I understand the problem,

Your env variable names aren't the same you use in the gatsby-config file.

in your .env file there's a key **GATSBY_ STOREFRONT_ACCESS_TOKEN** while in your gatsby-config is **GATSBY_SHOPIFY_ACCESS_TOKEN**.

**Comment by AlexanderProd** [comment]
Oh sorry, my bad. Thank you, works now!
